# GhostESP board profile seed — CrowPanel 9" ESP32-P4 V1.0
CONFIG_IDF_TARGET="esp32p4"
CONFIG_IDF_TARGET_ESP32P4=y

# Early P4 silicon (this board is rev v1.3)
CONFIG_ESP32P4_SELECTS_REV_LESS_V3=y
CONFIG_ESP32P4_REV_MIN_100=y

# Flash / PSRAM
CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y
CONFIG_ESPTOOLPY_FLASHSIZE="16MB"
CONFIG_SPIRAM=y
CONFIG_SPIRAM_MODE_HEX=y
CONFIG_SPIRAM_SPEED_200M=y

# GhostESP board identity + screen
CONFIG_BUILD_CONFIG_TEMPLATE="crowpanel_p4_9inch"
CONFIG_WITH_SCREEN=y
CONFIG_TFT_WIDTH=1024
CONFIG_TFT_HEIGHT=600

# Bluetooth: P4 has no local BT controller — NimBLE host runs on P4, controller
# is on the C6 over esp-hosted (HCI forwarded). Enable NimBLE so its headers
# (host/ble_gap.h) are available and GhostESP's BLE code compiles.
CONFIG_BT_ENABLED=y
CONFIG_BT_CONTROLLER_DISABLED=y
CONFIG_BT_NIMBLE_ENABLED=y

# Console
CONFIG_LOG_DEFAULT_LEVEL_INFO=y
CONFIG_ESP_CONSOLE_UART_DEFAULT=y

# --- LVGL config inherited from working crowtech7inch board ---
CONFIG_LV_CONF_SKIP=y
# CONFIG_LV_CONF_MINIMAL is not set
# CONFIG_LV_COLOR_DEPTH_32 is not set
CONFIG_LV_COLOR_DEPTH_16=y
# CONFIG_LV_COLOR_DEPTH_8 is not set
# CONFIG_LV_COLOR_DEPTH_1 is not set
CONFIG_LV_COLOR_DEPTH=16
CONFIG_LV_COLOR_16_SWAP=n
# CONFIG_LV_COLOR_SCREEN_TRANSP is not set
CONFIG_LV_COLOR_MIX_ROUND_OFS=128
CONFIG_LV_COLOR_CHROMA_KEY_HEX=0x00FF00
CONFIG_LV_MEM_CUSTOM=y
CONFIG_LV_MEM_CUSTOM_INCLUDE="stdlib.h"
CONFIG_LV_MEM_BUF_MAX_NUM=16
# CONFIG_LV_MEMCPY_MEMSET_STD is not set
CONFIG_LV_DISP_DEF_REFR_PERIOD=5
CONFIG_LV_INDEV_DEF_READ_PERIOD=30
# CONFIG_LV_TICK_CUSTOM is not set
CONFIG_LV_DPI_DEF=217
CONFIG_LV_DRAW_COMPLEX=y
CONFIG_LV_SHADOW_CACHE_SIZE=0
CONFIG_LV_CIRCLE_CACHE_SIZE=4
CONFIG_LV_LAYER_SIMPLE_BUF_SIZE=4800
CONFIG_LV_IMG_CACHE_DEF_SIZE=0
CONFIG_LV_GRADIENT_MAX_STOPS=2
CONFIG_LV_GRAD_CACHE_DEF_SIZE=0
# CONFIG_LV_DITHER_GRADIENT is not set
CONFIG_LV_DISP_ROT_MAX_BUF=1024
# CONFIG_LV_USE_GPU_ARM2D is not set
# CONFIG_LV_USE_GPU_STM32_DMA2D is not set
# CONFIG_LV_USE_GPU_RA6M3_G2D is not set
# CONFIG_LV_USE_GPU_SWM341_DMA2D is not set
# CONFIG_LV_USE_GPU_NXP_PXP is not set
# CONFIG_LV_USE_GPU_NXP_VG_LITE is not set
# CONFIG_LV_USE_GPU_SDL is not set
# CONFIG_LV_USE_LOG is not set
CONFIG_LV_USE_ASSERT_NULL=y
CONFIG_LV_USE_ASSERT_MALLOC=y
# CONFIG_LV_USE_ASSERT_STYLE is not set
# CONFIG_LV_USE_ASSERT_MEM_INTEGRITY is not set
# CONFIG_LV_USE_ASSERT_OBJ is not set
CONFIG_LV_ASSERT_HANDLER_INCLUDE="assert.h"
# CONFIG_LV_USE_PERF_MONITOR is not set
# CONFIG_LV_USE_REFR_DEBUG is not set
# CONFIG_LV_SPRINTF_CUSTOM is not set
# CONFIG_LV_SPRINTF_USE_FLOAT is not set
CONFIG_LV_USE_USER_DATA=y
# CONFIG_LV_ENABLE_GC is not set
# CONFIG_LV_BIG_ENDIAN_SYSTEM is not set
CONFIG_LV_ATTRIBUTE_MEM_ALIGN_SIZE=1
CONFIG_LV_ATTRIBUTE_FAST_MEM_USE_IRAM=y
# CONFIG_LV_USE_LARGE_COORD is not set
CONFIG_LV_FONT_MONTSERRAT_8=y
CONFIG_LV_FONT_MONTSERRAT_10=y
CONFIG_LV_FONT_MONTSERRAT_12=y
CONFIG_LV_FONT_MONTSERRAT_14=y
CONFIG_LV_FONT_MONTSERRAT_16=y
CONFIG_LV_FONT_MONTSERRAT_18=y
# CONFIG_LV_FONT_MONTSERRAT_20 is not set
# CONFIG_LV_FONT_MONTSERRAT_22 is not set
CONFIG_LV_FONT_MONTSERRAT_24=y
# CONFIG_LV_FONT_MONTSERRAT_26 is not set
# CONFIG_LV_FONT_MONTSERRAT_28 is not set
# CONFIG_LV_FONT_MONTSERRAT_30 is not set
# CONFIG_LV_FONT_MONTSERRAT_32 is not set
# CONFIG_LV_FONT_MONTSERRAT_34 is not set
# CONFIG_LV_FONT_MONTSERRAT_36 is not set
# CONFIG_LV_FONT_MONTSERRAT_38 is not set
CONFIG_LV_FONT_MONTSERRAT_40=y
# CONFIG_LV_FONT_MONTSERRAT_42 is not set
# CONFIG_LV_FONT_MONTSERRAT_44 is not set
# CONFIG_LV_FONT_MONTSERRAT_46 is not set
# CONFIG_LV_FONT_MONTSERRAT_48 is not set
# CONFIG_LV_FONT_MONTSERRAT_12_SUBPX is not set
# CONFIG_LV_FONT_MONTSERRAT_28_COMPRESSED is not set
# CONFIG_LV_FONT_DEJAVU_16_PERSIAN_HEBREW is not set
# CONFIG_LV_FONT_SIMSUN_16_CJK is not set
# CONFIG_LV_FONT_UNSCII_8 is not set
# CONFIG_LV_FONT_UNSCII_16 is not set
# CONFIG_LV_FONT_CUSTOM is not set
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_8 is not set
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_12 is not set
CONFIG_LV_FONT_DEFAULT_MONTSERRAT_14=y
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_16 is not set
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_18 is not set
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_20 is not set
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_22 is not set
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_24 is not set
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_26 is not set
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_28 is not set
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_30 is not set
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_32 is not set
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_34 is not set
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_36 is not set
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_38 is not set
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_40 is not set
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_42 is not set
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_44 is not set
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_46 is not set
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_48 is not set
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_12_SUBPX is not set
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_28_COMPRESSED is not set
# CONFIG_LV_FONT_DEFAULT_DEJAVU_16_PERSIAN_HEBREW is not set
# CONFIG_LV_FONT_DEFAULT_SIMSUN_16_CJK is not set
# CONFIG_LV_FONT_DEFAULT_UNSCII_8 is not set
# CONFIG_LV_FONT_DEFAULT_UNSCII_16 is not set
# CONFIG_LV_FONT_FMT_TXT_LARGE is not set
# CONFIG_LV_USE_FONT_COMPRESSED is not set
# CONFIG_LV_USE_FONT_SUBPX is not set
CONFIG_LV_USE_FONT_PLACEHOLDER=y
CONFIG_LV_TXT_ENC_UTF8=y
# CONFIG_LV_TXT_ENC_ASCII is not set
CONFIG_LV_TXT_BREAK_CHARS=" ,.;:-_"
CONFIG_LV_TXT_LINE_BREAK_LONG_LEN=0
CONFIG_LV_TXT_COLOR_CMD="#"
# CONFIG_LV_USE_BIDI is not set
# CONFIG_LV_USE_ARABIC_PERSIAN_CHARS is not set
CONFIG_LV_USE_ARC=y
# CONFIG_LV_USE_BAR is not set
CONFIG_LV_USE_BTN=y
CONFIG_LV_USE_BTNMATRIX=y
CONFIG_LV_USE_CANVAS=y
# CONFIG_LV_USE_CHECKBOX is not set
# CONFIG_LV_USE_DROPDOWN is not set
CONFIG_LV_USE_IMG=y
CONFIG_LV_USE_LABEL=y
CONFIG_LV_LABEL_TEXT_SELECTION=y
CONFIG_LV_LABEL_LONG_TXT_HINT=y
CONFIG_LV_USE_LINE=y
# CONFIG_LV_USE_ROLLER is not set
# CONFIG_LV_ROLLER_INF_PAGES is not set
# CONFIG_LV_USE_SLIDER is not set
# CONFIG_LV_USE_SWITCH is not set
# CONFIG_LV_USE_TEXTAREA is not set
# CONFIG_LV_TEXTAREA_DEF_PWD_SHOW_TIME is not set
# CONFIG_LV_USE_TABLE is not set
# CONFIG_LV_USE_ANIMIMG is not set
# CONFIG_LV_USE_CALENDAR is not set
# CONFIG_LV_CALENDAR_WEEK_STARTS_MONDAY is not set
CONFIG_LV_USE_CALENDAR_HEADER_ARROW=y
CONFIG_LV_USE_CALENDAR_HEADER_DROPDOWN=y
# CONFIG_LV_USE_CHART is not set
# CONFIG_LV_USE_COLORWHEEL is not set
# CONFIG_LV_USE_IMGBTN is not set
# CONFIG_LV_USE_KEYBOARD is not set
# CONFIG_LV_USE_LED is not set
CONFIG_LV_USE_LIST=y
# CONFIG_LV_USE_MENU is not set
# CONFIG_LV_USE_METER is not set
CONFIG_LV_USE_MSGBOX=y
# CONFIG_LV_USE_SPAN is not set
# CONFIG_LV_SPAN_SNIPPET_STACK_SIZE is not set
# CONFIG_LV_USE_SPINBOX is not set
# CONFIG_LV_USE_SPINNER is not set
# CONFIG_LV_USE_TABVIEW is not set
# CONFIG_LV_USE_TILEVIEW is not set
# CONFIG_LV_USE_WIN is not set
CONFIG_LV_USE_THEME_DEFAULT=y
# CONFIG_LV_THEME_DEFAULT_DARK is not set
CONFIG_LV_THEME_DEFAULT_GROW=y
CONFIG_LV_THEME_DEFAULT_TRANSITION_TIME=80
CONFIG_LV_USE_THEME_BASIC=y
# CONFIG_LV_USE_THEME_MONO is not set
CONFIG_LV_USE_FLEX=y
CONFIG_LV_USE_GRID=y
# CONFIG_LV_USE_FS_STDIO is not set
# CONFIG_LV_USE_FS_POSIX is not set
# CONFIG_LV_USE_FS_WIN32 is not set
# CONFIG_LV_USE_FS_FATFS is not set
# CONFIG_LV_USE_FS_LITTLEFS is not set
# CONFIG_LV_USE_PNG is not set
# CONFIG_LV_USE_BMP is not set
# CONFIG_LV_USE_SJPG is not set
CONFIG_LV_USE_GIF=y
# CONFIG_LV_USE_QRCODE is not set
# CONFIG_LV_USE_FREETYPE is not set
# CONFIG_LV_USE_TINY_TTF is not set
# CONFIG_LV_USE_RLOTTIE is not set
# CONFIG_LV_USE_FFMPEG is not set
# CONFIG_LV_USE_SNAPSHOT is not set
# CONFIG_LV_USE_MONKEY is not set
# CONFIG_LV_USE_GRIDNAV is not set
# CONFIG_LV_USE_FRAGMENT is not set
# CONFIG_LV_USE_IMGFONT is not set
# CONFIG_LV_USE_MSG is not set
# CONFIG_LV_USE_IME_PINYIN is not set
# CONFIG_LV_BUILD_EXAMPLES is not set
# CONFIG_LV_USE_DEMO_WIDGETS is not set
# CONFIG_LV_USE_DEMO_KEYPAD_AND_ENCODER is not set
# CONFIG_LV_USE_DEMO_BENCHMARK is not set
# CONFIG_LV_USE_DEMO_STRESS is not set
# CONFIG_LV_USE_DEMO_MUSIC is not set
CONFIG_LV_PREDEFINED_DISPLAY_NONE=y
# CONFIG_LV_PREDEFINED_DISPLAY_WROVER4 is not set
# CONFIG_LV_PREDEFINED_DISPLAY_M5STACK is not set
# CONFIG_LV_PREDEFINED_DISPLAY_M5CORE2 is not set
# CONFIG_LV_PREDEFINED_DISPLAY_M5STICK is not set
# CONFIG_LV_PREDEFINED_DISPLAY_M5STICKC is not set
# CONFIG_LV_PREDEFINED_DISPLAY_ERTFT0356 is not set
# CONFIG_LV_PREDEFINED_DISPLAY_ADA_FEATHERWING is not set
# CONFIG_LV_PREDEFINED_DISPLAY_RPI_MPI3501 is not set
# CONFIG_LV_PREDEFINED_DISPLAY_WEMOS_LOLIN is not set
# CONFIG_LV_PREDEFINED_DISPLAY_ATAG is not set
# CONFIG_LV_PREDEFINED_DISPLAY_RPI_RA8875 is not set
# CONFIG_LV_PREDEFINED_DISPLAY_TTGO is not set
# CONFIG_LV_PREDEFINED_DISPLAY_TTGO_CAMERA_PLUS is not set
# CONFIG_LV_PREDEFINED_DISPLAY_WT32_SC01 is not set
CONFIG_LV_TFT_DISPLAY_CONTROLLER_ILI9341=y
CONFIG_LV_TFT_DISPLAY_PROTOCOL_SPI=y
CONFIG_LV_HOR_RES_MAX=240
CONFIG_LV_VER_RES_MAX=320
CONFIG_LV_DISPLAY_ORIENTATION_PORTRAIT=y
# CONFIG_LV_DISPLAY_ORIENTATION_PORTRAIT_INVERTED is not set
# CONFIG_LV_DISPLAY_ORIENTATION_LANDSCAPE is not set
# CONFIG_LV_DISPLAY_ORIENTATION_LANDSCAPE_INVERTED is not set
CONFIG_LV_DISPLAY_ORIENTATION=0
CONFIG_LV_PREDEFINED_PINS_NONE=y
# CONFIG_LV_PREDEFINED_PINS_38V4 is not set
# CONFIG_LV_PREDEFINED_PINS_30 is not set
# CONFIG_LV_PREDEFINED_PINS_38V1 is not set
# CONFIG_LV_PREDEFINED_PINS_TKOALA is not set
CONFIG_LV_TFT_DISPLAY_USER_CONTROLLER_ILI9341=y
# CONFIG_LV_TFT_DISPLAY_USER_CONTROLLER_ILI9481 is not set
# CONFIG_LV_TFT_DISPLAY_USER_CONTROLLER_ILI9486 is not set
# CONFIG_LV_TFT_DISPLAY_USER_CONTROLLER_ILI9488 is not set
# CONFIG_LV_TFT_DISPLAY_USER_CONTROLLER_ST7789 is not set
# CONFIG_LV_TFT_DISPLAY_USER_CONTROLLER_ST7796S is not set
# CONFIG_LV_TFT_DISPLAY_USER_CONTROLLER_GC9A01 is not set
# CONFIG_LV_TFT_DISPLAY_USER_CONTROLLER_ST7735S is not set
# CONFIG_LV_TFT_DISPLAY_USER_CONTROLLER_HX8357 is not set
# CONFIG_LV_TFT_DISPLAY_USER_CONTROLLER_SH1107 is not set
# CONFIG_LV_TFT_DISPLAY_USER_CONTROLLER_SSD1306 is not set
# CONFIG_LV_TFT_DISPLAY_USER_CONTROLLER_FT81X is not set
# CONFIG_LV_TFT_DISPLAY_USER_CONTROLLER_IL3820 is not set
# CONFIG_LV_TFT_DISPLAY_USER_CONTROLLER_JD79653A is not set
# CONFIG_LV_TFT_DISPLAY_USER_CONTROLLER_UC8151D is not set
# CONFIG_LV_TFT_DISPLAY_USER_CONTROLLER_RA8875 is not set
# CONFIG_LV_TFT_DISPLAY_USER_CONTROLLER_ILI9163C is not set
# CONFIG_LV_TFT_DISPLAY_USER_CONTROLLER_PCD8544 is not set
CONFIG_LV_TFT_DISPLAY_SPI2_HOST=y
# CONFIG_LV_TFT_DISPLAY_SPI3_HOST is not set
CONFIG_LV_TFT_DISPLAY_SPI_TRANS_MODE_SIO=y
# CONFIG_LV_TFT_DISPLAY_SPI_TRANS_MODE_DIO is not set
# CONFIG_LV_TFT_DISPLAY_SPI_TRANS_MODE_QIO is not set
CONFIG_LV_TFT_DISPLAY_SPI_HALF_DUPLEX=y
# CONFIG_LV_TFT_DISPLAY_SPI_FULL_DUPLEX is not set
CONFIG_LV_TFT_USE_CUSTOM_SPI_CLK_DIVIDER=y
# CONFIG_LV_TFT_SPI_CLK_DIVIDER_1 is not set
CONFIG_LV_TFT_SPI_CLK_DIVIDER_2=y
# CONFIG_LV_TFT_SPI_CLK_DIVIDER_3 is not set
# CONFIG_LV_TFT_SPI_CLK_DIVIDER_4 is not set
# CONFIG_LV_TFT_SPI_CLK_DIVIDER_5 is not set
# CONFIG_LV_TFT_SPI_CLK_DIVIDER_6 is not set
# CONFIG_LV_TFT_SPI_CLK_DIVIDER_7 is not set
# CONFIG_LV_TFT_SPI_CLK_DIVIDER_8 is not set
# CONFIG_LV_TFT_SPI_CLK_DIVIDER_9 is not set
# CONFIG_LV_TFT_SPI_CLK_DIVIDER_10 is not set
# CONFIG_LV_TFT_SPI_CLK_DIVIDER_12 is not set
# CONFIG_LV_TFT_SPI_CLK_DIVIDER_16 is not set
# CONFIG_LV_TFT_SPI_CLK_DIVIDER_20 is not set
# CONFIG_LV_TFT_SPI_CLK_DIVIDER_24 is not set
# CONFIG_LV_TFT_SPI_CLK_DIVIDER_32 is not set
# CONFIG_LV_TFT_SPI_CLK_DIVIDER_40 is not set
# CONFIG_LV_TFT_SPI_CLK_DIVIDER_48 is not set
# CONFIG_LV_TFT_SPI_CLK_DIVIDER_80 is not set
CONFIG_LV_TFT_CUSTOM_SPI_CLK_DIVIDER=2
# CONFIG_LV_INVERT_COLORS is not set
CONFIG_LV_DISP_SPI_MOSI=23
CONFIG_LV_DISPLAY_USE_SPI_MISO=y
CONFIG_LV_DISP_SPI_MISO=19
CONFIG_LV_DISP_SPI_INPUT_DELAY_NS=0
CONFIG_LV_DISP_SPI_CLK=18
CONFIG_LV_DISPLAY_USE_SPI_CS=y
CONFIG_LV_DISP_SPI_CS=17
CONFIG_LV_DISPLAY_USE_DC=y
CONFIG_LV_DISP_PIN_DC=16
CONFIG_LV_DISP_USE_RST=y
CONFIG_LV_DISP_PIN_RST=5
# CONFIG_LV_DISP_BACKLIGHT_OFF is not set
CONFIG_LV_DISP_BACKLIGHT_SWITCH=y
# CONFIG_LV_DISP_BACKLIGHT_PWM is not set
CONFIG_LV_BACKLIGHT_ACTIVE_LVL=y
CONFIG_LV_DISP_PIN_BCKL=32
CONFIG_LV_I2C=y
CONFIG_LV_I2C_DISPLAY_PORT=0
CONFIG_LV_TOUCH_CONTROLLER=7
# CONFIG_LV_TOUCH_CONTROLLER_NONE is not set
# CONFIG_LV_TOUCH_CONTROLLER_XPT2046 is not set
# CONFIG_LV_TOUCH_CONTROLLER_FT6X06 is not set
# CONFIG_LV_TOUCH_CONTROLLER_STMPE610 is not set
# CONFIG_LV_TOUCH_CONTROLLER_ADCRAW is not set
# CONFIG_LV_TOUCH_CONTROLLER_FT81X is not set
# CONFIG_LV_TOUCH_CONTROLLER_RA8875 is not set
CONFIG_LV_TOUCH_CONTROLLER_GT911=y
CONFIG_LV_I2C_TOUCH=y
# CONFIG_LV_GT911_SWAPXY is not set
# CONFIG_LV_GT911_INVERT_X is not set
# CONFIG_LV_GT911_INVERT_Y is not set
CONFIG_LV_I2C_TOUCH_PORT_0=y
# CONFIG_LV_I2C_TOUCH_PORT_1 is not set
CONFIG_LV_I2C_TOUCH_PORT=0

# 16MB OTA partition layout (app is 3.26MB; needs >3MB slots)
CONFIG_PARTITION_TABLE_CUSTOM=y
CONFIG_PARTITION_TABLE_CUSTOM_FILENAME="partitions_ota_16mb.csv"

# ESP-Hosted (C6 WiFi coprocessor) needs 1000 Hz FreeRTOS tick
CONFIG_FREERTOS_HZ=1000

# Shrink esp-hosted SDIO RX buffers (streaming mode over-allocates internal DMA
# RAM and asserts at boot). We do not need the C6 link for the GhostLink relay.
CONFIG_ESP_HOSTED_SDIO_OPTIMIZATION_RX_STREAMING_MODE=n
CONFIG_ESP_HOSTED_SDIO_RX_Q_SIZE=8
CONFIG_ESP_HOSTED_SDIO_TX_Q_SIZE=8

# Screen OFF for now: GhostESP display manager uses SPI/RGB drivers; the EK79007
# MIPI-DSI panel needs a DSI path wired into GhostESP LVGL (next task). Headless
# boot (serial CLI) confirms the core port is stable.
CONFIG_WITH_SCREEN=y

# Re-enable screen: EK79007 DSI now wired into GhostESP display_manager.
CONFIG_WITH_SCREEN=y
# DSI panel takes native RGB565 byte order (no swap; swap is for the SPI panels)
CONFIG_LV_COLOR_16_SWAP=n

# Enable GhostESP touch polling (GT911 read wired in display_manager for P4)
CONFIG_USE_TOUCHSCREEN=y

# --- Onboard ESP32-C6 WiFi via esp-hosted (Elecrow V1.0 verified wiring) ---
# Backlight is GPIO31 (not GhostESP's default 32); GPIO32 is the C6 SDIO reset.
CONFIG_LV_DISP_PIN_BCKL=31
# esp-hosted SDIO link to the C6 — values from Elecrow's working WiFi lesson:
CONFIG_ESP_HOSTED_SDIO_1_BIT_BUS=y
CONFIG_ESP_HOSTED_SDIO_BUS_WIDTH=1
CONFIG_ESP_HOSTED_SDIO_PIN_CLK=18
CONFIG_ESP_HOSTED_SDIO_PIN_CMD=19
CONFIG_ESP_HOSTED_SDIO_PIN_D0=14
CONFIG_ESP_HOSTED_SDIO_PIN_D1=15
CONFIG_ESP_HOSTED_SDIO_GPIO_RESET_SLAVE=32
CONFIG_ESP_HOSTED_SDIO_RESET_ACTIVE_HIGH=y
CONFIG_ESP_HOSTED_SDIO_RESET_DELAY_MS=1500
CONFIG_ESP_HOSTED_SLAVE_RESET_ON_EVERY_HOST_BOOTUP=y

# --- BLE over the onboard C6 (esp-hosted VHCI, not UART HCI) ---
# GhostESP defaults NimBLE to a UART HCI transport, which aborts on P4
# ("UART driver already installed"). Route NimBLE's HCI over esp-hosted's VHCI
# to the C6 controller instead.
CONFIG_BT_NIMBLE_TRANSPORT_UART=n
CONFIG_ESP_HOSTED_ENABLE_BT_NIMBLE=y
CONFIG_ESP_HOSTED_NIMBLE_HCI_VHCI=y
